# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 19:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='is user active?', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email_verified', models.BooleanField(default=False, help_text='is user email verified?', verbose_name='email verified')),
                ('is_verified', models.BooleanField(default=False, help_text='is user identity verified?', verbose_name='verified')),
                ('user_type', models.CharField(choices=[(0, 'developer'), (1, 'manager'), (2, 'educator'), (3, 'student')], default=3, max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserAccountAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=254, verbose_name='unique code')),
                ('action_type', models.IntegerField(verbose_name='action type')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('expires', models.DateTimeField(default=datetime.datetime(2017, 10, 11, 19, 8, 6, 901459, tzinfo=utc), verbose_name='expires')),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='last modified')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('belongs_to_user', models.ForeignKey(help_text='belongs to user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
