# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=254, verbose_name='unique code')),
                ('action_type', models.IntegerField(verbose_name='action type')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='last modified')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('belongs_to_user', models.ForeignKey(help_text='belongs to user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
